### ISSUE TITLE
Add features: task 3

### ISSUE THREAD

**Issue by HalfSealHalfCat** [Dobrovenskis/infa_2020_dobrovenskis#1]
[In task 3](https://github.com/Dobrovenskis/infa_2020_dobrovenskis/blob/master/Lab3/sea.ipynb)

1. Add transparency for different objects.
2. Create at least two types of boats.
3. Add waves on the sea, optionally animate it.

**Comment by Kolin48** [comment]
### Изменил файл sea.ipynb. (в lab3)

1. Добавил прозрачность облакам (10, 15-22 строка). 
2. Добавил ещё 1 тип лодки ( 44-60).
3.  Добавил волны (119 - 127). 
4. Сделал анимацию (130-148 и 170-180). 
5. Часть анимации сохранил в sea.GIF.gif
